### ISSUE TITLE
Script to convert "old" Zarrs to JPEG-XL

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/Satip#81]
## Possible Implementation
Hopefully it's a case of loading the "old" Zarrs, and:

* rename `stacked_eumetsat_data` to `data`
* convert values to `float32`
* convert `-1` values to NaN
* divide by 1023 to get values in the range `[0, 1]`
* pass to `utils.save_dataset_to_zarr` with `compressor_name='jpeg-xl'`
* UPDATE: Jacob suggests: "run the same deduplication code as in nowcasting_dataset"
* UPDATE: Jacob suggests: "making the spatial chunks larger, especially for HRV data."

**Comment by jacobbieker** [comment]
I would also include running the same deduplication code as in nowcasting_dataset, because the code for checking if a timestep existed already before appending to the dataset was wrong until recently, there is almost certainly quite a few redundant timesteps. 

Additionally, I would also go with making the spatial chunks larger, especially for HRV data.

**Comment by jacobbieker** [comment]
A script is now running to convert doing all of these things

**Comment by JackKelly** [comment]
I assume we can close this issue now? (Please re-open if I've misunderstood!)
