### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/Satip#9]
## Detailed Description
We should add more unit tests for the repo, downloading, etc.

## Context
Unit tests are good

## Possible Implementation
Possibly pass in the key and secret through GH Repo secrets? Then it could try downloading some data, etc.

**Comment by jacobbieker** [comment]
Plotting has some unit tests, need to add them for checking that time period already exists or not (I am not convinced it is currently working...)

**Comment by notger** [comment]
As mentioned over at https://github.com/openclimatefix/Satip/issues/72, I would be a taker for this one. I like writing tests. :)

You mentioned above the problem of passing secrets.
But the API-keys are personalised, so I guess the best way would be to provide a detailed instruction where to get your own set of API-keys when you want to contribute to development, instead of semi-hard-coding the keys via e.g. git-secrets. What do you think?

**Comment by jacobbieker** [comment]
Actually, I've added the keys as secrets here, so I think it's good so that the tests can be run with actual data on the ci tests. But also, adding to the readme how  to get your own keys would be great too!

**Comment by notger** [comment]
Ah, cool, had not seen that keys had been added, but had not really looked. 

Will add a section on how to get your keys, as I got them yesterday and let's say the documentation from Eumetsat is comprehensive and slightly unforgiving. At least to me it seemed. ;)

**Comment by peterdudfield** [comment]
thanks @notger for doing this

**Comment by notger** [comment]
No worries, my pleasure. However, this weekend I came down with Covid and the fun-factor in that is limited. So I don't guess I will get much done this week.

**Comment by notger** [comment]
Would suggest to close this issue as well, see discussion in issue #72 .
More unit testing does seem neither feasible nor sensible.

**Comment by peterdudfield** [comment]
Happy to close, keeps the conversation tidy
